apiVersion: v1
kind: Service
metadata:
  name: smg-service
  labels:
    app: smg
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: {{ .Values.TARGET_PORT }}
      protocol: TCP
  selector:
    app: smg