---
- hosts: staging_master
  vars:
    user: "{{- lookup('env','docker_user') -}}"
  tasks:
    - name: Fail if $docker_user is not set on master
      fail:
        msg: $docker_user environment variable should be set to docker registry user
      when: user == ""

    - name: Create docker group if not exists
      become: true
      shell: getent group docker || groupadd docker

    - name: Permit docker usage
      become: true
      user: name=ubuntu groups=docker append=yes
      notify:
        - Reset connection

    - name: chown .docker
      become: true
      file:
        path: .docker
        owner: ubuntu
        group: docker

    - name: Copy docker credentials
      copy:
        src: token.txt
        dest: ./
        owner: ubuntu
      register: token

    - name: Login to docker from CLI
      shell: "cat token.txt | docker login https://docker.pkg.github.com -u {{ user }} --password-stdin"

    - name: Delete docker credentials
      file:
        path: token.txt
        state: absent

    - name: Get existing secrets
      shell: kubectl get secrets -o name -n smg
      register: secrets

    - name: Delete existing secret if token changed
      shell: kubectl delete secret docker-secret -n smg
      when: secrets.stdout.find("secret/docker-secret") != -1 and token.changed

    - name: Generate docker secret for kube
      shell: kubectl create secret generic docker-secret --from-file=.dockerconfigjson=.docker/config.json --type=kubernetes.io/dockerconfigjson -n smg

  handlers:
    - name: Reset connection
      shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
      async: 3
      poll: 2