name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  env:
    PATH: /home/runner/.local/bin:$PATH
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -v -r requirements.txt

      - name: Test all
        run: pytest
