name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -v -r requirements.txt

      - name: Run pylint
        run: pytest --pylint

      - name: Test all
        run: pytest --cov=./ --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
